#.travis.yml

language: node_js
node_js:
  - "10"
dist: trusty
sudo: false

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_script:
  - npm install -g @angular/cli

script:
  - ng lint
  - ng build --prod --base-href https://dlevkov.github.io/ng7-virtual-scroll/
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: dist/virtual-scroll

notifications:
  email:
    on_failure: change
    on_success: change
